-- Clear existing sports configs and insert all active sports from Diamond API
TRUNCATE TABLE public.sports_sid_configs;

-- Insert all active sports with tab=true (primary sports to show)
INSERT INTO public.sports_sid_configs (sport_type, sid, label, icon, is_active, is_default, display_order) VALUES
('cricket', '4', 'Cricket', '🏏', true, true, 1),
('football', '1', 'Football', '⚽', true, false, 2),
('tennis', '2', 'Tennis', '🎾', true, false, 3),
('kabaddi', '66', 'Kabaddi', '🤼', true, false, 5),
('esoccer', '68', 'Esoccer', '⚽', true, false, 6),
('horse-racing', '10', 'Horse Racing', '🏇', true, false, 7),
('greyhound-racing', '65', 'Greyhound Racing', '🐕', true, false, 8),
('basketball', '15', 'Basketball', '🏀', true, false, 9),
('wrestling', '69', 'Wrestling', '🤼', true, false, 10),
('volleyball', '18', 'Volleyball', '🏐', true, false, 11),
('badminton', '22', 'Badminton', '🏸', true, false, 12),
('snooker', '59', 'Snooker', '🎱', true, false, 13),
('darts', '57', 'Darts', '🎯', true, false, 14),
('boxing', '6', 'Boxing', '🥊', true, false, 15),
('mma', '3', 'Mixed Martial Arts', '🥋', true, false, 16),
('american-football', '58', 'American Football', '🏈', true, false, 17),
('e-games', '11', 'E Games', '🎮', true, false, 18),
('ice-hockey', '19', 'Ice Hockey', '🏒', true, false, 19),
('futsal', '9', 'Futsal', '⚽', true, false, 20),
('motor-sports', '52', 'Motor Sports', '🏎️', true, false, 22),
('politics', '40', 'Politics', '🗳️', true, false, 23),
('golf', '5', 'Golf', '⛳', true, false, 25),
('rugby-league', '55', 'Rugby League', '🏉', true, false, 26),
('beach-volleyball', '7', 'Beach Volleyball', '🏐', true, false, 27),
('handball', '39', 'Handball', '🤾', true, false, 29),
('motogp', '16', 'MotoGP', '🏍️', true, false, 31),
('chess', '17', 'Chess', '♟️', true, false, 32),
('formula1', '23', 'Formula 1', '🏎️', true, false, 35),
('cycling', '29', 'Cycling', '🚴', true, false, 41),
('motorbikes', '32', 'Motorbikes', '🏍️', true, false, 44),
('athletics', '33', 'Athletics', '🏃', true, false, 45),
('basketball-3x3', '35', 'Basketball 3X3', '🏀', true, false, 47),
('sumo', '37', 'Sumo', '🤼', true, false, 49),
('virtual-sports', '38', 'Virtual Sports', '🎮', true, false, 50),
('baseball', '53', 'Baseball', '⚾', true, false, 62),
('rugby-union', '54', 'Rugby Union', '🏉', true, false, 63),
('soccer', '62', 'Soccer', '⚽', true, false, 67),
('esports', '64', 'Esports', '🎮', true, false, 69);